name: Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: rashelshah
          filename: github-metrics.svg

          base: header, activity, repositories

          plugin_languages: yes
          plugin_languages_limit: 8

          plugin_isocalendar: yes

          plugin_activity: yes
          plugin_activity_limit: 5
